name: Workflow

on:
  push:
    branches:
      - main
  
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: npm install

      - name: Test
        run: 'make test'
      
      - name: Lint
        run: 'make lint'
